// Single source of truth for component data — loaded by index.html (frontend) AND api/suggest.js (AI).
export const COMPONENTS=[
{id:"bentom",name:"Grid Section — Bento M",cat:"feature_grids",ct:"gridSection",cthint:"set Variant = bento_M",vfield:"fields.variant",variant:"bento_M",pillars:["standard_setter","translation_of_complexity","thought_leader","authority","trust_anchor"],chips:["standard_setter","translation_of_complexity","thought_leader"],cd:false,density:"medium",media:"image, icon",
kw:["overview","grid","bento","feature","features","benefit","benefits","cards","capabilities","process","steps","flow","logo","logos","partner","partners","partnership","explanation","explain","describe","each with text"],
purpose:"Mainly an overview grid for a group of related points; can also show a light numbered flow or a link collection.",
tip:"Use product images or icons and explain each point in a Bento M card. Need step numbers for a flow? Put them in the image, icon or heading.",
assets:"Per card: 1 image (16:10) OR 1 icon — optional · 2–9 cards",
assetReqs:[{l:"Card image or icon",s:"image 16:10, or an icon",req:false,ic:"img"}],
budget:[["Section eyebrow","32 characters","opt"],["Section heading","~60 characters","opt"],["Section paragraph","1–2 sentences","opt"],["Card heading (each)","80 characters, required","req"],["Card paragraph (each)","short, 1–2 sentences","opt"],["Card link text","~25 characters (optional)","opt"],["Cards","2–9 (ideal 3 or 6)"]],
uses:["Overview / feature or benefit grid (main purpose)","Partner / certification logos each with a short explanation (logo image + heading + paragraph per card) — when a Trust Section's logo-only strip isn't enough","Light numbered flow (numbers in image/icon/heading)","Link collection (e.g. to blog posts) → Thought-Leader character"],
str:["Flexible — carries many content types and almost any pillar","Image OR icon per card + short text","Optional link per card","2–9 items, ideal 3 or 6"],
lim:["Card heading hard-capped at 80 chars","For pure trust-building, others fit better","With >6 items the grid gets busy"],
anti:"For a real step-by-step process the Steps Section is better. Not as a primary trust element."},

{id:"video",name:"1-Column Section — Video",cat:"content_single",ct:"oneColumnSection",cthint:"set Media = Video",pillars:["standard_setter","trust_anchor","translation_of_complexity","thought_leader","authority"],chips:[],cd:true,density:"low",media:"video",
kw:["video","explainer","demo","testimonial","pov","watch","play","film","clip","process","product","flow","screen","screen recording","walkthrough","how it works","in-product"],
purpose:"Gives one statement room and backs it with a video — explainer, demo, testimonial or POV.",
tip:"Screen-record the flow in Candis and show it as a video — the moving product makes a process concrete and proves it works.",
assets:"1 video (file, YouTube or Wistia) + 1 thumbnail image (16:9) — both required",
assetReqs:[{l:"Video",s:"File, YouTube or Wistia",req:true,ic:"play"},{l:"Thumbnail image",s:"16:9 ratio",req:true,ic:"img",note:"the play-button shouldn't cover essential elements"}],
budget:[["Section eyebrow","~32 characters","opt"],["Section heading","~60 characters","opt"],["Section paragraph","1–2 sentences","opt"],["Video display title","~60 characters","opt"],["Video meta description","~150–160 characters","req"],["Video duration","5 characters (e.g. “5 min”)","req"],["Play-button alt text","short","req"],["Link text","~25 characters (optional)","opt"]],
uses:["Product explainer / demo video","Testimonial / customer story as video","Founder / vision POV video","One video center stage with framing copy"],
str:["A single focal point — no competition","Video shows instead of tells","Three hosting options: file, YouTube, Wistia","Lots of real estate — for especially important videos"],
lim:["Can't carry multiple parallel points (use Grid/Bento)","Video adds load weight (esp. mobile)"],
anti:"Not for multiple parallel features. Not for step-by-step with proof per step. Don't bury the video under heavy copy."},

{id:"image",name:"1-Column Section — Image",cat:"content_single",ct:"oneColumnSection",cthint:"set Media = Image",pillars:["standard_setter","trust_anchor","translation_of_complexity","thought_leader","authority"],chips:[],cd:true,density:"low",media:"image",
kw:["image","photo","picture","screenshot","visual","editorial","brand","diagram","illustration","product"],
purpose:"Gives one statement room and supports it with a single strong image — editorial, brand or explanatory.",
tip:"Use one strong product screenshot or brand image and let the heading + paragraph carry the point. A labelled diagram works great here too.",
assets:"1 image — required (ratio free, always full component width) · optional separate mobile image · provide alt text",
assetReqs:[{l:"Image",s:"free ratio · full component width",req:true,ic:"img"},{l:"Mobile image",s:"optional separate image",req:false,ic:"img"}],
budget:[["Section eyebrow","~32 characters","opt"],["Section heading","~60 characters","opt"],["Section paragraph","1–2 sentences","opt"],["Image alt text","~125 characters","opt"],["Image title","~60 characters","opt"],["Link text","~25 characters (optional)","opt"]],
uses:["Editorial / brand image moment","Diagram or before/after visual","Product screenshot as a focal proof","One important image center stage with framing copy"],
str:["A single focal point","Lots of real estate for one important image","Lighter than video — faster load","Built-in alt text (accessibility + SEO)"],
lim:["A static image shows less than a video","Can't carry multiple parallel points","Strongly image-dependent"],
anti:"Not for multiple parallel features. Not for step-by-step. Don't use a purely decorative image where proof/explanation is needed."},

{id:"toolcmp",name:"1-Column Section — Table (Tool Comparison)",cat:"content_single",ct:"oneColumnSection",cthint:"set Media = Table, Variant = tool_comparison",pillars:["standard_setter","trust_anchor"],chips:["standard_setter","trust_anchor"],cd:false,density:"medium",media:"table",
kw:["compare","comparison","versus","vs","candis vs","competitor","competitors","alternative","alternatives","others","checkmark","feature by feature","table","tool comparison"],
purpose:"A comparison table that pits Candis against other tools, feature by feature, with green checkmarks and red crosses.",
tip:"List the features that matter, check Candis, and be honest with a red cross where a competitor leads — it makes the whole table more believable.",
assets:"No images required",
assetReqs:[],
budget:[["Section eyebrow","~32 characters","opt"],["Section heading","~60 characters","opt"],["Section paragraph","1–2 sentences","opt"],["Column headers","short, ~15–20 characters","req"],["Feature labels","concise, ~60 characters","req"],["Section header tag","short (optional)","opt"]],
uses:["Whenever the messaging wants a “Candis vs …” angle","Candis vs competitor tools, feature by feature","Candis features vs the market standard","A long matrix that needs collapsing / accordion"],
str:["Side-by-side reads as “we measure up”","Honest red crosses build credibility","Accordion + collapse-by-default keep it compact","Checks / crosses scan fast"],
lim:["Needs accurate, maintained competitive data","Dense — too many rows/columns overwhelm","2–4 comparison columns max (+ label column)"],
anti:"Not for non-comparative content. Don't make claims you can't back up. Don't overload with columns/rows."},

{id:"decision",name:"1-Column Section — Table (Decision Overview)",cat:"content_single",ct:"oneColumnSection",cthint:"set Media = Table, Variant = decision_overview",pillars:["standard_setter","trust_anchor"],chips:["standard_setter","trust_anchor"],cd:false,density:"high",media:"table",
kw:["compare","comparison","versus","vs","candis vs","competitor","alternative","others","nuanced","context","decision","it depends","trade-off","tradeoff","table","fit"],
purpose:"A text-based comparison table for nuanced, not-black-and-white comparisons; leaves the “right fit” call to the reader.",
tip:"When it's not black-and-white, write a sentence per cell on what each option really offers and let the reader decide — that reads as honest.",
assets:"No images required",
assetReqs:[],
budget:[["Section eyebrow","~32 characters","opt"],["Section heading","~60 characters","opt"],["Section paragraph","1–2 sentences","opt"],["Column headers","short, ~15–20 characters","req"],["Cell text","a sentence or two","req"],["Category labels","short (selectable categories)","opt"]],
uses:["Whenever the messaging wants a “Candis vs …” angle (nuanced)","Nuanced comparison where “it depends”","Explaining trade-offs / fit by use case","A multi-category decision overview (selectable categories)"],
str:["Free text per cell → room for nuance","Reads as honest → builds trust","Selectable categories keep it navigable","Sets the criteria that matter"],
lim:["Text-heavy → can get long","Needs accurate, maintained context","Less instantly scannable than a checkmark table"],
anti:"Not when a simple yes/no comparison is enough (use Tool Comparison). Don't let cells become walls of text."},

{id:"cta",name:"CTA Section",cat:"conversion",ct:"ctaSection",cthint:"link a CTA Button (click) or a Form (sign-up)",pillars:["standard_setter","trust_anchor","translation_of_complexity","thought_leader","authority"],chips:["trust_anchor"],cd:true,density:"low",media:"image (optional)",
kw:["cta","call to action","sign up","signup","sign-up","email","newsletter","consultation","demo","book","convert","conversion","download","button","form","waitlist","lead","contact"],
purpose:"A conversion section that drives one action — click a button (e.g. book a consultation) or sign up via a form (e.g. email).",
tip:"Pick one action. For a low-friction ask use a button (“book a free consultation”); to capture leads use the email form.",
assets:"Optional: 1 image — upload 16:10, but the copy sets the component height, so the image is stretched/cropped to a different ratio · copy & graphic must be briefed together",
assetReqs:[{l:"Image",s:"upload 16:10 · copy sets height, may crop",req:false,ic:"img"}],
budget:[["Section eyebrow","32 characters","opt"],["Section heading","52 characters (punchy)","opt"],["Section paragraph","120 characters","opt"],["Button text","~25 characters","req"],["Form success / error msgs","short, 1 line each","req"],["Privacy policy","as needed (form mode)","opt"]],
uses:["“Book a consultation / demo” button (or Demodesk form)","Newsletter / waitlist email sign-up","Gated content download (PDF on submit)","End-of-page conversion ask"],
str:["Two modes: button click OR inline form","Form covers consultation booking, email, gated PDF","Optional image + background colours","Focused, single ask"],
lim:["Should carry one clear ask","Form mode needs a linked form entry","Keep CTA copy tight"],
anti:"Don't stack multiple competing CTAs. Don't use it as a content section. Don't bury the action under long copy."},

{id:"beforeafter",name:"Before / After Slider",cat:"process",ct:"customComponent",cthint:"set Component variant = before_after_slider",vfield:"fields.componentVariant",variant:"before_after_slider",pillars:["translation_of_complexity","trust_anchor","standard_setter"],chips:["translation_of_complexity"],cd:false,density:"medium",media:"image",
kw:["before","after","before/after","transformation","workflow","ohne und mit","slider","reveal","drag","change","pain","relief","process","product"],
purpose:"An interactive before/after comparison across 3–4 paired Bento M cards — drag to reveal on desktop, toggle on mobile.",
tip:"Pair each “before” pain with its “after” relief across 3–4 cards; visitors drag (or toggle on mobile) to feel the change.",
assets:"Before: 3–4 images (16:10) + After: 3–4 images (16:10) — required, one per Bento M card",
assetReqs:[{l:"Before images",s:"3–4 × 16:10",req:true,ic:"img"},{l:"After images",s:"3–4 × 16:10",req:true,ic:"img"}],
budget:[["Section eyebrow","~32 characters","opt"],["Section heading","~60 characters","opt"],["Section paragraph","1–2 sentences","opt"],["Before / after headings","short, ~24 characters (desktop)","opt"],["Card heading (each)","80 characters","req"],["Card paragraph (each)","short, 1–2 sentences","opt"],["Mobile toggle labels","short","opt"]],
uses:["“Ohne und mit Candis” workflow comparison","Showing pain (before) → relief (after) across steps","Any before/after transformation story"],
str:["Interactive reveal makes the contrast memorable","3–4 paired cards cover a multi-step transformation","Shows, not tells","Before = recognisable pain, after = Candis relief"],
lim:["Needs paired before/after content per card","Interaction differs desktop (drag) vs mobile (toggle)","Lives inside customComponent — less discoverable"],
anti:"Not for non-transformation content. Don't mismatch the before/after card counts."},

{id:"exitintent",name:"Exit Intent Modal",cat:"conversion",ct:"customComponent",cthint:"set Component variant = exit_intent_modal, then link a Modal and pick its variant",vfield:"fields.componentVariant",variant:"exit_intent_modal",pillars:["trust_anchor","standard_setter"],chips:[],cd:true,density:"low",media:"image (optional)",
kw:["exit intent","exit-intent","modal","popup","pop-up","overlay","deal","offer","summer deal","end of year","end-of-year","urgency","urgent","countdown","timer","survey","limited time","banner","leave","exit","promo"],
purpose:"An overlay that surfaces one urgent or high-value ask over the page — a limited-time deal, a survey, or a booking prompt. Pops up on exit or after X seconds, globally or on chosen pages.",
tip:"Use it for time-sensitive asks — e.g. a deal with a live countdown that pops up when a visitor moves to leave (or after a set number of seconds). The action can be a button or an email capture.",
assets:"Optional: 1 image — 1:1 (square) ratio; shown beside the text",
assetReqs:[{l:"Image",s:"1:1 (square)",req:false,ic:"img"}],
budget:[["Eyebrow","~32 characters","opt"],["Heading","~50 characters","opt"],["Title","~50 characters, required","req"],["Close label","short, required","req"],["Paragraph","1–2 sentences","opt"],["Button text","~25 characters","opt"],["Reassurance text","short line","opt"]],
uses:["Summer / end-of-year deal with a countdown","Short survey or feedback prompt","“Book a consultation” prompt (→ Demodesk)","Time-limited announcement on exit or after X seconds"],
str:["Appears over any page without touching its layout","Placement control: globally by page type, or specific pages","Timing control — on exit and/or after X seconds","Built-in countdown banner for genuine urgency"],
lim:["Two-level setup — wrapper customComponent plus a linked Modal entry","Interruptive — overuse trains visitors to dismiss it","No character limits set in Contentful"],
anti:"Don't run it everywhere all the time or stack multiple modals on one page — keep it to one clear, worth-interrupting ask. Don't use it as a regular content section."},

{id:"feedback",name:"Feedback Section",cat:"conversion",ct:"customComponent",cthint:"set Component variant = feedback_section, link a Common Text Set + fill Suggestions",vfield:"fields.componentVariant",variant:"feedback_section",pillars:["thought_leader","trust_anchor"],chips:["thought_leader"],cd:false,density:"medium",media:"none",
kw:["feedback","survey","poll","topic","topics","ideas","idea box","suggestion","suggestions","ask visitors","engagement","input","vote","what do you want","community","podcast topics","blog ideas"],
purpose:"Ask visitors for input — which topics interest them or what challenges them. They pick a suggested topic chip or write their own (~150 chars); responses land in Slack (#website-feedback-form-submit).",
tip:"Use it to ask your audience what they want next — seed a few topic chips and let them add their own. Great on blog/podcast pages to source editorial ideas straight from readers.",
assets:"None (UI only — no images)",
assetReqs:[],
budget:[["Section eyebrow","~32 characters","opt"],["Section heading","~60 characters","opt"],["Section paragraph","2–3 sentences","opt"],["Suggestion chips","short, ~25 characters each (a few)","opt"],["UI labels (choose one / or your own)","short","opt"],["Textarea placeholder","short","opt"],["Submit button","~25 characters","opt"],["Visitor free-text","~150 characters (their input)"],["Success message","short, 1 line","opt"]],
uses:["“Which topics should we cover next?” on a blog / podcast page","Gather pain points or feature wishes","A lightweight idea box / mini survey","Source editorial ideas directly from readers"],
str:["Two ways to answer — pick a suggested chip OR write your own","Responses flow straight to Slack (#website-feedback-form-submit)","Signals you listen → builds rapport","Low-friction, one focused ask"],
lim:["Links a Common Text Set for all UI microcopy","Free-text answer is short (~150 characters)","Needs the Slack submission endpoint wired (backend)","Not a lead/contact form — no email capture"],
anti:"Don't use it as a contact / lead-capture form (no email field). Don't overload it with too many suggestion chips. Don't ask for feedback you won't act on."},

{id:"banner",name:"Page Bottom Banner",cat:"conversion",ct:"customComponent",cthint:"set Component variant = page_bottom_banner, set the expiry date (drives the countdown), link a CTA button, and choose global or specific pages",vfield:"fields.componentVariant",variant:"page_bottom_banner",pillars:["trust_anchor","standard_setter"],chips:[],cd:true,density:"low",media:"none",
kw:["banner","bottom banner","sticky","countdown","timer","deal","offer","event","webinar","registration","sign up","limited time","end of year","date","deadline","urgency","announcement","footer"],
purpose:"A sticky countdown banner pinned to the bottom of the screen (dismissible) for anything tied to a date — a deal, webinar or event — with a live countdown + CTA. Shows globally or on selected pages.",
tip:"Use it for a date-driven push (webinar / event / deal) that follows the visitor while scrolling — set the expiry date and it counts down. Less interruptive than a modal.",
assets:"None (text + countdown + button)",
assetReqs:[],
budget:[["Heading","~50 characters (punchy)","opt"],["Paragraph (date/time + line)","1 short sentence","opt"],["CTA button","~25 characters","opt"]],
uses:["Webinar / event registration with a countdown","Limited-time deal counting down to the deadline","Any date-driven announcement that stays visible while scrolling"],
str:["Stays visible while scrolling without blocking the page","Built-in live countdown creates urgency","Dismissible — visitors can close it","Flexible placement: global by page type, or specific pages","One clear ask (heading + countdown + CTA)"],
lim:["Needs an expiry date to count down to","Persistent footer uses a little screen space until dismissed","One message at a time"],
anti:"Don't use it for evergreen content (no date = no countdown). Don't stack multiple persistent banners. Don't keep it running past the deadline."},

{id:"steps",name:"Steps Section",cat:"process",ct:"customComponent",cthint:"set Component variant = steps_section, add exactly 3 Bento M (with images) under steps, optional button",vfield:"fields.componentVariant",variant:"steps_section",pillars:["translation_of_complexity","standard_setter"],chips:["translation_of_complexity"],cd:false,density:"medium",media:"image (3 cards)",
kw:["steps","step","process","timeline","how it works","onboarding","implementation","rollout","phases","stages","day 1","sequence","walkthrough"],
purpose:"A 3-step process/timeline: exactly three Bento M cards as steps (with step labels like Heute → Tag 14 → Tag 30), each with an image, heading and a short checklist. Optional button below.",
tip:"Use it to show how something unfolds over time — set a step label per card (the timeline marker), an image, a heading and a short checklist. Exactly 3 steps, images required.",
assets:"3 images (16:10), one per step — required (icon variant does NOT work here)",
assetReqs:[{l:"Step images",s:"3 × 16:10 (one per step) · icon doesn't work",req:true,ic:"img"}],
budget:[["Section eyebrow","~32 characters","opt"],["Section heading","~60 characters","opt"],["Section paragraph","1–2 sentences (optional)","opt"],["Step label (each)","short, ~12 characters","opt"],["Card heading (each)","80 characters","req"],["Card checklist (each)","short bullet lines","opt"],["Button","~25 characters","opt"],["Steps","exactly 3"]],
uses:["“So läuft die Implementierung” — onboarding / rollout timeline","A 3-phase how-it-works","Before → during → after of a workflow, as discrete steps"],
str:["Reads instantly as a time-ordered process (timeline + step labels)","Each step gets an image + heading + scannable checklist","Optional closing CTA (e.g. download a guide)","Turns a process into three digestible beats"],
lim:["Exactly 3 steps — fewer/more breaks the design (Dusan to harden)","Images required — the icon variant doesn't work here","Each step is a Bento M, inheriting its card limits"],
anti:"Not for non-sequential content (use a Grid Section). Don't try to fit 4+ steps. Don't leave out the images (icon-only breaks the layout)."},

{id:"bentoxl",name:"Bento XL",cat:"content_single",ct:"bentoXL",cthint:"set Media (image 1:1 transparent, or video, or custom HTML), pick a Background + Image position, add a button / text link",pillars:["trust_anchor","standard_setter","translation_of_complexity","thought_leader","authority"],chips:[],cd:true,density:"medium",media:"image (1:1) / video / custom HTML",
kw:["bento","bento xl","feature section","image and text","split section","showcase","integration","datev","sesam","navattic","custom html","embed","two column","feature","background","video","video with text","explainer","demo","explanation","walkthrough"],
purpose:"A large feature section: a 1:1 visual (image, video, or custom HTML embed like Navattic) beside text (eyebrow, heading, paragraph) with an optional button + text link. Several background styles; image left or right. Stands alone or inside a Grid Section.",
tip:"Use it to give one feature or story a generous spotlight beside a square visual — set the image 1:1 with a transparent background (Contentful sets the bg), pick a background variant, and place the image left or right. Swap the image for a video or a custom HTML embed (e.g. Navattic).",
assets:"Media required — 1 image 1:1 (square, transparent bg set in Contentful), or a video, or a custom HTML embed",
assetReqs:[{l:"Visual",s:"1:1 transparent image, a video, or custom HTML",req:true,ic:"img"}],
budget:[["Eyebrow","~40 · 270 max","opt"],["Heading","~60 · 620 max","req"],["Paragraph","1–3 sentences","req"],["Button text","~25 characters","opt"],["Text link","~25 characters (optional)","opt"]],
uses:["A standalone feature/story section (image + text + CTA)","A video or product demo with explanatory copy beside it (alternative to the 1-Column Video when you want text next to the video)","Showcase an integration or capability (e.g. Sesam + DATEV export)","Embed an interactive product demo via custom HTML (Navattic)","A bento placed inside a larger Grid Section"],
str:["Flexible media: a 1:1 image, a video, or a custom HTML embed","Six background styles + image left/right for visual variety","Generous heading/eyebrow room; supports a button + a text link","Works standalone or inside a Grid Section"],
lim:["Image must be 1:1 with a transparent background (bg set in Contentful)","Media is required","The Icon field does nothing here (it's for the Bento Tab Section)"],
anti:"Don't use a non-square or non-transparent image (the background won't show through correctly). Don't rely on the Icon field for the standalone Bento XL."},

{id:"trust",name:"Trust Section",cat:"content_single",ct:"customComponent",cthint:"set Component variant = trust_section, add trustSectionItems (logo/badge images) and/or platformRatings (rated platforms with stars + link)",vfield:"fields.componentVariant",variant:"trust_section",pillars:["trust_anchor","standard_setter"],chips:["trust_anchor"],cd:false,density:"low",media:"logos / badges (images) · or platform ratings",
kw:["trust","proof","social proof","logos","logo","partner","partners","partnership","certification","certified","badge","badges","ratings","reviews","stars","capterra","google","app store","datev","credibility","awards","trusted by"],
purpose:"A short proof strip — partner/certification logos, badges, or platform ratings (stars). 2–8 items; auto-loops as a slider if they overflow the width.",
tip:"Drop in 2–8 partner/cert logos as image files, or use Platform Ratings for star scores with a link (Capterra, Google…). If every logo must be visible at once, a Grid Section “logos” variant fits better.",
assets:"2–8 logo/badge image files (auto-loops as a slider if they overflow); or Platform Ratings (image + star + link)",
assetReqs:[{l:"Logo / badge images",s:"2–8 image files · auto-loops as a slider on overflow",req:true,ic:"img"},{l:"Platform ratings",s:"alternative — image + star rating + link (Capterra, Google…)",req:false,ic:"img"}],
budget:[["Section eyebrow","~32 characters","opt"],["Section heading","~60 characters","opt"],["Items","2–8 (more → auto-slider)"]],
uses:["Partner / certification logos (“Candis als offizieller Partner von”)","Customer ratings with stars (Capterra, Google, App Store…)","Badges / trust marks / awards","A proof strip near a conversion point"],
str:["Quick social-proof strip — partners, certs or ratings","Auto-loops as a slider when items overflow the width","Items can be plain logos OR rated platforms (stars + link)","Works with 2 to ~8 items"],
lim:["No copy per item — just ONE eyebrow + heading for the whole strip; the logos carry no text. If each partner/logo needs its own explanation, use a Grid Section — Bento M instead (logo/image + heading + paragraph per card).","If every item MUST be visible at once (no slider), or each logo should deep-link to its own page, the Grid Section — Logos (Integrations) variant fits better","Logos need clean, consistent image files","Ratings need Platform Ratings entries (image + rating + url)"],
anti:"Don't reach for it when each logo needs an explanation — there's no per-item text, only logos under one shared heading; use a Bento M grid for logo + copy. Don't cram so many logos that the auto-slider hides key ones (use a logos grid). Don't use unrelated or low-trust logos."},
{id:"logosint",name:"Grid Section — Logos (Integrations)",cat:"feature_grids",ct:"gridSection",cthint:"set Variant = logos_b; add each integration to content as a Link entry (appearance = media: logo image + link to that integration's subpage); the “not listed?” side card comes from commonTextSet + ctaButton",vfield:"fields.variant",variant:"logos_b",pillars:["standard_setter","trust_anchor"],chips:["standard_setter"],cd:false,density:"low",media:"integration logo image files — each links to its subpage",
 kw:["integration","integrations","integrate","integrated","connected","connect","logos","logo","schnittstelle","schnittstellen","api","rest api","oauth","json","export","exports","datev","addison","agenda","sesam","erp","sap","sage","dynamics","business central","accounting software","buchhaltung","buchhaltungssoftware","ecosystem","tools","stack","compatible","compatibility","qualification","fit"],
 purpose:"A grid of integration/partner logos — shows which accounting & ERP systems Candis connects to, grouped (common systems / ERP / Candis interface). Each logo deep-links to its integration subpage, so a prospect instantly sees “they fit my stack.”",
 tip:"Standing component — the integrations rarely change, so it's reused as-is; you normally don't rewrite the copy. Pick the relevant logos, group them, keep the eyebrow + heading and the “not listed? → open API” side card.",
 assets:"One Link entry per integration (appearance = media): a clean logo image + a link to that integration's subpage. Grouped: DATEV & adjacent, ERP, Candis interface. Plus the “not listed?” side card (commonTextSet + a CTA link).",
 assetReqs:[{l:"Integration logos",s:"one Link entry each (appearance = media): logo image + link to its subpage · 3–8 per section",req:true,ic:"img"},{l:"“Not listed?” side card",s:"commonTextSet — short paragraph + API / OAuth / JSON chips + a CTA link (Mehr zur Schnittstelle)",req:false,ic:"img"}],
 budget:[["Section eyebrow","32 characters","opt"],["Section heading","~60 characters","opt"],["Logo label (each)","short brand name","opt"],["Side-card paragraph","~200 characters","opt"],["Logos","3–8 per section (curate & group)"]],
 uses:["Show which accounting / ERP systems Candis integrates with (DATEV & adjacent, ERP, own interface)","Prospect qualification — “they connect to my system, good fit”","Deep-link each logo to its integration subpage","A “not listed?” side card pointing to the open Candis API (REST / OAuth / JSON)"],
 str:["Instant ecosystem proof — recognizable accounting / ERP logos","Each logo deep-links to its own integration subpage","Standing component — set up once, rarely needs changes","Side card answers the “my system isn't here” objection (open API)"],
 lim:["Logos need clean, consistent image files — and each needs a target subpage to link to","3–8 logos per section — curate & group rather than dumping every integration","It's a logo + link grid, not a text grid — for a short explanation per item use a Grid Section — Bento M"],
 anti:"Don't rewrite it per page — the integrations are stable, reuse the standing section. Don't add a logo without a target subpage, and don't cram every integration in; group the relevant ones (DATEV & adjacent / ERP / interface)."},
{id:"faq",name:"FAQ Section",cat:"content_single",ct:"faqSection",cthint:"add a heading, then up to 30 faqQuestion entries — each is a question (plain text) + a rich-text answer (lists, links, headings allowed)",vfield:"",variant:"",pillars:["translation_of_complexity","trust_anchor"],chips:["translation_of_complexity"],cd:true,density:"high",media:"none — text only (built for SEO & AI crawlers)",
 kw:["faq","faqs","faq section","questions","answers","q&a","q and a","accordion","objection","objections","concerns","häufige fragen","fragen","antworten","seo","search","ranking","rich results","structured data","schema","ai crawlers","ai crawler","llm","answer engine","generative search","offload text","reduce text","common questions","help","explainer"],
 purpose:"A heading + an accordion of up to 30 question/answer pairs. Built for SEO and AI crawlers (structured Q&A that search & answer engines surface) and to keep pages lean — move detailed text into the FAQ instead of bloating the page copy.",
 tip:"Answer the questions prospects actually ask (and search) — security, data, access, pricing concerns. The rich-text answers can hold lists, links and headings, so park detail here instead of stuffing it into the page. Phrasing questions like real search queries is what helps SEO + AI crawlers most.",
 assets:"None — text only: a question (plain text) + a rich-text answer per item.",
 assetReqs:[],
 budget:[["Section heading","~60 characters","opt"],["Question (each)","no hard limit · phrase like a real search query","req"],["Answer (each)","rich text · no limit (lists, links, headings, embeds)","opt"],["Questions","1–30 per section"]],
 uses:["Answer recurring prospect questions / objections (security, data, access…)","SEO — structured Q&A that search engines surface as rich results","Feed AI crawlers / answer engines clean question–answer pairs","Offload detail from a page — park it in the FAQ instead of bloating the copy"],
 str:["Purpose-built for SEO & AI crawlers — structured question/answer pairs","Rich-text answers (lists, links, headings) hold real detail","Keeps pages lean — move long explanations into the accordion","Up to 30 questions; reusable across topics"],
 lim:["Text only — no images or media","Answers are collapsed by default, so don't hide must-see info inside them","Questions worded as real search queries help SEO/AI most — internal phrasing won't"],
 anti:"Don't dump marketing fluff — FAQs work when they answer real questions plainly. Don't bury critical info (pricing, key features) only inside a collapsed FAQ. Don't paste the same Q&A across many pages verbatim — duplicate/thin content hurts SEO."},
{id:"bentoxs",name:"Grid Section — Bento XS",cat:"feature_grids",ct:"gridSection",cthint:"set Variant = bento_XS; add 2–5 Bento XS to bentoBoxesXS, set an icon + heading per box (paragraph / eyebrow / scroll-to a Bento XL are optional)",vfield:"fields.variant",variant:"bento_XS",pillars:["translation_of_complexity","standard_setter"],chips:["translation_of_complexity"],cd:true,density:"low",media:"icon only (no images)",
 kw:["bento","bento xs","xs","grid","compact","small","mini","feature","features","highlights","icons","icon","overview","at a glance","navigation","page nav","anchor","jump to","scroll to","capabilities","quick facts"],
 purpose:"The smallest bento: 2–5 compact cards, each an icon + short heading + one-line paragraph. Icons only (no images). A box can also act as in-page navigation — “On Click scroll to” anchors down to a Bento XL on the same page.",
 tip:"Use for a tight row of features/highlights (icon + a few words), or as in-page navigation. Keep copy short — heading ≤38, paragraph ≤130. Heads up: the “scroll to” target can ONLY be a Bento XL, not an arbitrary section or page (see limitations).",
 assets:"One icon per card (an image entry used as an icon) — 2–5 cards. No photographic images.",
 assetReqs:[{l:"Card icons",s:"one icon (image entry) per card · 2–5 cards · icons only, no images",req:true,ic:"img"}],
 budget:[["Section eyebrow","32 characters","opt"],["Section heading","~60 characters","opt"],["Section paragraph","rich text (optional)","opt"],["Card eyebrow (each)","16 characters","opt"],["Card heading (each)","38 characters","req"],["Card paragraph (each)","130 characters","opt"],["Cards","2–5 per section"]],
 uses:["A compact row of features / highlights (icon + a few words)","In-page navigation — a card scroll-jumps to a Bento XL further down","A quick “at a glance” capability strip"],
 str:["Smallest, tightest bento — icon + heading + one line","2–5 cards in a clean row","Can double as in-page navigation (scroll to a Bento XL)","Forces concise copy (heading ≤38, paragraph ≤130)"],
 lim:["Icons only — no images (use Bento S/M/L for images)","Very tight copy: heading ≤38, paragraph ≤130 chars","⚠️ “On Click scroll to” can ONLY target a Bento XL — not an arbitrary page or section (Contentful restricts the field to bentoXL)","Needs 2–5 cards — not for a single highlight"],
 anti:"Don't try to fit a full sentence — XS is an icon + a few words. Don't expect images. Don't rely on it to jump anywhere other than a Bento XL anchor."},
{id:"bentos",name:"Grid Section — Bento S",cat:"feature_grids",ct:"gridSection",cthint:"set Variant = bento_S; add Bento S to bentoBoxesS (4 / 8 / 12), set image or icon or topLineColor",vfield:"fields.variant",variant:"bento_S",pillars:["translation_of_complexity","standard_setter"],chips:["translation_of_complexity"],cd:true,density:"low",media:"icon, image, or a colored top line (choose one) — all optional",
 kw:["bento","bento s","small","grid","feature","features","cards","benefit","benefits","highlights","icon","image","colored line","top line","color","text link","four","4-up","compact","overview"],
 purpose:"Small cards in a grid (4 / 8 / 12, laid out in rows of 4). Each card: a heading + short paragraph + optional text link, with your choice of an icon, an image, or a colored line on top.",
 tip:"Use for a row (or rows) of small feature/benefit cards. Per card you can pick ONE visual: an icon, an image, or a colored top line (a hex colour) — or none. Keep heading ≤65, paragraph ≤130, and add a text link if the card should lead somewhere. Cards come in fours.",
 assets:"Per card (optional): one icon (image entry) OR one image OR a colored top line (a hex value, no file). Plus an optional text link.",
 assetReqs:[{l:"Card icon or image",s:"optional · one icon (image entry) or one image per card",req:false,ic:"img"},{l:"Colored top line",s:"optional alternative to icon/image — a hex colour bar on top (topLineColor), no file needed",req:false,ic:"code"},{l:"Text link",s:"optional · a link per card",req:false,ic:"code"}],
 budget:[["Section eyebrow","32 characters","opt"],["Section heading","~60 characters","opt"],["Section paragraph","rich text (optional)","opt"],["Card heading (each)","65 characters","req"],["Card paragraph (each)","130 characters","opt"],["Top line colour","hex value, e.g. #895fd5","opt"],["Card link text","short label","opt"],["Cards","4 / 8 / 12 — rows of 4"]],
 uses:["A row (or rows) of small feature / benefit cards","Compact highlights where each card needs a heading + a line + a link","Cards set apart by a colored top line instead of an icon/image"],
 str:["Small, flexible cards — icon, image, OR a colored top line per card","Holds more cards than the others (4 / 8 / 12…)","Optional text link per card","Heading up to 65 + a short paragraph"],
 lim:["Lays out in rows of 4 — 4 / 8 / 12 look balanced (odd counts leave a ragged row)","One visual per card — an icon, image or colored line, not several at once","Tight paragraph (≤130 chars)"],
 anti:"Don't mix visual treatments randomly across cards if it looks messy — keep them consistent. Don't overfill small cards with long copy. Don't use odd counts that leave a half-empty last row."},
{id:"bentol",name:"Grid Section — Bento L",cat:"feature_grids",ct:"gridSection",cthint:"set Variant = bento_L; add 2 or 4 Bento L to bentoBoxesL, set a 16:10 image + heading per box (paragraph and link optional)",vfield:"fields.variant",variant:"bento_L",pillars:["translation_of_complexity","standard_setter"],chips:["translation_of_complexity"],cd:true,density:"medium",media:"image (16:10) — required, one per card",
 kw:["bento","bento l","large","big","grid","image","images","16:10","photo","picture","visual","feature","features","benefit","benefits","cards","two","four","image card"],
 purpose:"Image-led cards in a grid (2 or 4, laid out in rows of 2). Each card pairs a 16:10 image with a short heading + a brief line, plus an optional link. The most visual of the in-grid bentos.",
 tip:"Use when each point needs a real image (16:10) beside it. Copy is tight — heading ≤23, paragraph ≤70 — so let the image carry the weight. 2 or 4 cards (rows of 2). Add a link per card if it should lead somewhere.",
 assets:"One 16:10 image per card (required) — 2 or 4 cards. Optional link per card.",
 assetReqs:[{l:"Card image",s:"one 16:10 image per card · required · 2 or 4 cards",req:true,ic:"img"},{l:"Card link",s:"optional · a link per card",req:false,ic:"code"}],
 budget:[["Section eyebrow","32 characters","opt"],["Section heading","~60 characters","opt"],["Section paragraph","rich text (optional)","opt"],["Card heading (each)","23 characters","req"],["Card paragraph (each)","70 characters","opt"],["Card link text","short label","opt"],["Cards","2 or 4 — rows of 2"]],
 uses:["Image-led feature / benefit cards (a picture per point)","A small set of highlights where the visual matters most","Two or four cards in a clean 2-up layout"],
 str:["Most visual of the small bentos — a 16:10 image per card","Clean 2-up layout (2 or 4 cards)","Optional link per card","Image carries the message, so copy stays short"],
 lim:["Image is required — no icon-only or text-only cards","Very tight copy: heading ≤23 (the shortest of all bentos), paragraph ≤70","Lays out in rows of 2 — use 2 or 4 (3 leaves a ragged row)"],
 anti:"Don't use it without good 16:10 images — the image is the point. Don't try to cram copy; the heading is only 23 characters. Don't use odd counts that leave a half-empty row."},
{id:"bentoxlsticky",name:"Grid Section — Bento XL Sticky Scroll",cat:"feature_grids",ct:"gridSection",cthint:"set Variant = bento_XL_sticky_scroll; add several Bento XL to bentoBoxesXL, give each a media (image/video) + heading + paragraph (the media stays pinned while its text scrolls)",vfield:"fields.variant",variant:"bento_XL_sticky_scroll",pillars:["translation_of_complexity","thought_leader"],chips:["translation_of_complexity"],cd:true,density:"high",media:"one image (or video) per Bento XL — stays sticky while its text scrolls, then swaps",
 kw:["bento xl","sticky","sticky scroll","scrollytelling","scroll","story","storytelling","journey","walkthrough","guided","narrative","deep dive","step by step","a lot to say","long","pinned image","reveal"],
 purpose:"A long-form, scroll-driven story: several Bento XL stacked, where the media stays pinned while you scroll each block's text and the visual swaps to match. For when you have a LOT to say and want to guide visitors through it step by step.",
 tip:"Best for taking visitors on a journey — a guided walkthrough where each step has its own big visual and you control the reveal. Because people can't see what's ahead, keep it focused and use it sparingly (sticky scroll can disorient). If they should see all the topics at a glance, use the Bento XL Tab Section instead.",
 assets:"One media per Bento XL — an image (or video / custom HTML) that stays pinned while its text scrolls; a few Bento XL in sequence.",
 assetReqs:[{l:"Media per block",s:"one image (or video / custom HTML) per Bento XL · required · stays pinned while text scrolls",req:true,ic:"img"},{l:"Links",s:"optional · up to two links per block",req:false,ic:"code"}],
 budget:[["Section eyebrow","32 characters","opt"],["Section heading","~60 characters","opt"],["Section paragraph","rich text (optional)","opt"],["Block eyebrow (each)","270 characters","opt"],["Block heading (each)","620 characters","req"],["Block paragraph (each)","rich text — no limit","req"],["Blocks","several Bento XL (up to ~10)"]],
 uses:["A guided product walkthrough — each step gets its own big visual","Storytelling a transformation or customer journey (problem → solution, before → after)","A deep feature explanation where every point deserves a large visual + dwell time","A screen-by-screen flow where the image/video updates per step (great with UI shots)","Taking visitors on a narrative where you control the order and the reveal"],
 str:["Holds a LOT — several full Bento XL blocks of copy + visuals","Sticky media keeps the visual in view while the story scrolls","The visual swaps per block — strong for step-by-step or screen-by-screen flows","Controls the reveal — great for journeys/storytelling (you don't see what's next)","Works with image, video or custom HTML media"],
 lim:["Overuse disorients — sticky scroll hides where you are; keep it focused, ideally one per page","Visitors can't see what's coming — if they need all topics at a glance, use the Bento XL Tab Section","Heavy: needs real content and a strong visual per block","Long-form — not for a quick, scannable overview"],
 anti:"Don't use it for a short list or quick overview — that's what scannable grids/tabs are for. Don't stack several sticky-scroll sections on one page (people lose orientation). Don't leave a block without a meaningful visual — the swapping media is the whole point."}
];
